---------------------------------
---东方梦无垠程序库
---
---
---
tuolib=tuolib or {}
---梦无垠自机
Include'TUOlib\\TUO_Player\\TUO_Player.lua'
---复杂动画
Include'TUOlib\\exani\\exani_player_manager.lua'
---梦现指针系统
Include'TUOlib\\DR_Pin_System\\DR_Pin_System.lua'
---3d背景处理器
Include'TUOlib\\TUO_Background\\TUO_Background.lua'
---mod和关卡管理器
Include'TUOlib\\Mod_Stage_Manager\\Mod_Manager.lua'
---特效开关
Include'TUOlib\\Effect_Cut.lua'
---开发者工具和UI
Include'TUOlib\\Dev_Tool\\Dev_Tool.lua'
